package com.angel.shz.dbservice.mapper;

import com.angel.shz.dbservice.model.Commodityimagerelatiton;
import com.angel.shz.dbservice.model.CommodityimagerelatitonExample;
import com.angel.shz.dbservice.model.CommodityimagerelatitonKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityimagerelatitonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int countByExample(CommodityimagerelatitonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int deleteByExample(CommodityimagerelatitonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CommodityimagerelatitonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int insert(Commodityimagerelatiton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int insertSelective(Commodityimagerelatiton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    List<Commodityimagerelatiton> selectByExample(CommodityimagerelatitonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    Commodityimagerelatiton selectByPrimaryKey(CommodityimagerelatitonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Commodityimagerelatiton record, @Param("example") CommodityimagerelatitonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Commodityimagerelatiton record, @Param("example") CommodityimagerelatitonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Commodityimagerelatiton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimagerelatiton
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Commodityimagerelatiton record);
}