package com.angel.shz.dbservice.mapper;

import com.angel.shz.dbservice.model.Commodityimage;
import com.angel.shz.dbservice.model.CommodityimageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityimageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int countByExample(CommodityimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int deleteByExample(CommodityimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int insert(Commodityimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int insertSelective(Commodityimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    List<Commodityimage> selectByExample(CommodityimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    Commodityimage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Commodityimage record, @Param("example") CommodityimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Commodityimage record, @Param("example") CommodityimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Commodityimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodityimage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Commodityimage record);
}