package com.angel.shz.dbservice.mapper;

import com.angel.shz.dbservice.model.Commodity;
import com.angel.shz.dbservice.model.CommodityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int countByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int deleteByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int insertSelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    List<Commodity> selectByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    Commodity selectByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Commodity record);
}