package com.angel.shz.dbservice.mapper;

import com.angel.shz.dbservice.model.Finishorder;
import com.angel.shz.dbservice.model.FinishorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FinishorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int countByExample(FinishorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int deleteByExample(FinishorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int insert(Finishorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int insertSelective(Finishorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    List<Finishorder> selectByExample(FinishorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    Finishorder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Finishorder record, @Param("example") FinishorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Finishorder record, @Param("example") FinishorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Finishorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shz..finishorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Finishorder record);
}