package com.angel.shz.dbservice.model;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..area.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..area.sheng
     *
     * @mbggenerated
     */
    private String sheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..area.shi
     *
     * @mbggenerated
     */
    private String shi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..area.quxian
     *
     * @mbggenerated
     */
    private String quxian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..area.xiangzhen
     *
     * @mbggenerated
     */
    private String xiangzhen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..area.jiedao
     *
     * @mbggenerated
     */
    private String jiedao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..area.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..area.normal_address
     *
     * @mbggenerated
     */
    private Integer normalAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..area.id
     *
     * @return the value of shz..area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..area.id
     *
     * @param id the value for shz..area.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..area.sheng
     *
     * @return the value of shz..area.sheng
     *
     * @mbggenerated
     */
    public String getSheng() {
        return sheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..area.sheng
     *
     * @param sheng the value for shz..area.sheng
     *
     * @mbggenerated
     */
    public void setSheng(String sheng) {
        this.sheng = sheng == null ? null : sheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..area.shi
     *
     * @return the value of shz..area.shi
     *
     * @mbggenerated
     */
    public String getShi() {
        return shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..area.shi
     *
     * @param shi the value for shz..area.shi
     *
     * @mbggenerated
     */
    public void setShi(String shi) {
        this.shi = shi == null ? null : shi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..area.quxian
     *
     * @return the value of shz..area.quxian
     *
     * @mbggenerated
     */
    public String getQuxian() {
        return quxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..area.quxian
     *
     * @param quxian the value for shz..area.quxian
     *
     * @mbggenerated
     */
    public void setQuxian(String quxian) {
        this.quxian = quxian == null ? null : quxian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..area.xiangzhen
     *
     * @return the value of shz..area.xiangzhen
     *
     * @mbggenerated
     */
    public String getXiangzhen() {
        return xiangzhen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..area.xiangzhen
     *
     * @param xiangzhen the value for shz..area.xiangzhen
     *
     * @mbggenerated
     */
    public void setXiangzhen(String xiangzhen) {
        this.xiangzhen = xiangzhen == null ? null : xiangzhen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..area.jiedao
     *
     * @return the value of shz..area.jiedao
     *
     * @mbggenerated
     */
    public String getJiedao() {
        return jiedao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..area.jiedao
     *
     * @param jiedao the value for shz..area.jiedao
     *
     * @mbggenerated
     */
    public void setJiedao(String jiedao) {
        this.jiedao = jiedao == null ? null : jiedao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..area.user_id
     *
     * @return the value of shz..area.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..area.user_id
     *
     * @param userId the value for shz..area.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..area.normal_address
     *
     * @return the value of shz..area.normal_address
     *
     * @mbggenerated
     */
    public Integer getNormalAddress() {
        return normalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..area.normal_address
     *
     * @param normalAddress the value for shz..area.normal_address
     *
     * @mbggenerated
     */
    public void setNormalAddress(Integer normalAddress) {
        this.normalAddress = normalAddress;
    }
}