package com.angel.shz.dbservice.model;

public class Commodityimagerelatiton extends CommodityimagerelatitonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..commodityimagerelatiton.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..commodityimagerelatiton.type
     *
     * @return the value of shz..commodityimagerelatiton.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..commodityimagerelatiton.type
     *
     * @param type the value for shz..commodityimagerelatiton.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}