package com.angel.shz.dbservice.model;

public class CommodityimagerelatitonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..commodityimagerelatiton.commodity_num
     *
     * @mbggenerated
     */
    private Integer commodityNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..commodityimagerelatiton.commodityImage_id
     *
     * @mbggenerated
     */
    private Integer commodityimageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..commodityimagerelatiton.commodity_num
     *
     * @return the value of shz..commodityimagerelatiton.commodity_num
     *
     * @mbggenerated
     */
    public Integer getCommodityNum() {
        return commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..commodityimagerelatiton.commodity_num
     *
     * @param commodityNum the value for shz..commodityimagerelatiton.commodity_num
     *
     * @mbggenerated
     */
    public void setCommodityNum(Integer commodityNum) {
        this.commodityNum = commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..commodityimagerelatiton.commodityImage_id
     *
     * @return the value of shz..commodityimagerelatiton.commodityImage_id
     *
     * @mbggenerated
     */
    public Integer getCommodityimageId() {
        return commodityimageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..commodityimagerelatiton.commodityImage_id
     *
     * @param commodityimageId the value for shz..commodityimagerelatiton.commodityImage_id
     *
     * @mbggenerated
     */
    public void setCommodityimageId(Integer commodityimageId) {
        this.commodityimageId = commodityimageId;
    }
}