package com.angel.shz.dbservice.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.ordercol
     *
     * @mbggenerated
     */
    private String ordercol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.commodity_num
     *
     * @mbggenerated
     */
    private Integer commodityNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.commodity_amount
     *
     * @mbggenerated
     */
    private BigDecimal commodityAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shz..order.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.id
     *
     * @return the value of shz..order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.id
     *
     * @param id the value for shz..order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.status
     *
     * @return the value of shz..order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.status
     *
     * @param status the value for shz..order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.create_time
     *
     * @return the value of shz..order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.create_time
     *
     * @param createTime the value for shz..order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.user_id
     *
     * @return the value of shz..order.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.user_id
     *
     * @param userId the value for shz..order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.ordercol
     *
     * @return the value of shz..order.ordercol
     *
     * @mbggenerated
     */
    public String getOrdercol() {
        return ordercol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.ordercol
     *
     * @param ordercol the value for shz..order.ordercol
     *
     * @mbggenerated
     */
    public void setOrdercol(String ordercol) {
        this.ordercol = ordercol == null ? null : ordercol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.commodity_num
     *
     * @return the value of shz..order.commodity_num
     *
     * @mbggenerated
     */
    public Integer getCommodityNum() {
        return commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.commodity_num
     *
     * @param commodityNum the value for shz..order.commodity_num
     *
     * @mbggenerated
     */
    public void setCommodityNum(Integer commodityNum) {
        this.commodityNum = commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.commodity_amount
     *
     * @return the value of shz..order.commodity_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCommodityAmount() {
        return commodityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.commodity_amount
     *
     * @param commodityAmount the value for shz..order.commodity_amount
     *
     * @mbggenerated
     */
    public void setCommodityAmount(BigDecimal commodityAmount) {
        this.commodityAmount = commodityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.price
     *
     * @return the value of shz..order.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.price
     *
     * @param price the value for shz..order.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shz..order.area_id
     *
     * @return the value of shz..order.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shz..order.area_id
     *
     * @param areaId the value for shz..order.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }
}